FROM rust:latest

WORKDIR /build

RUN apt-get update && apt-get install -y build-essential && \
    rm -rf /var/lib/apt/lists/*

RUN cargo install cargo-deb

COPY . .

RUN cargo build --release && cargo deb

RUN mkdir -p /output && \
    for file in $(find target -name "*.deb"); do \
        base=$(basename "$file" .deb) && \
        cp "$file" "/output/${base}_amd64.deb"; \
    done

FROM scratch
COPY --from=0 /output/*.deb /